[package]
name = "clog"
version = "0.1.0"
authors = ["Mohammed Alateyya <mnur@cmu.edu>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop =  { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
im-rc = "15.0.0"