[package]
name = "mylang"
version = "0.1.0"
authors = ["Mohammed Alateyya <mnur@cmu.edu>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16"

[dependencies]
lalrpop-util = "0.16"
regex = "1.0.5"